# Generated by Django 3.0.8 on 2020-07-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BedRoomCategoryy',
            new_name='BedRoomCategory',
        ),
    ]
